SELECT CAST(DT_TRAMITACAO AS DATE) AS DATA, DEPARTAMENTO, COUNT(*) AS TOTAL
FROM  `view_hist_processos`
WHERE
  IS_RECEBIDO = 1 AND
  CAST(DT_TRAMITACAO AS DATE) BETWEEN ('2017-1-1') AND ('2017-12-7')
GROUP BY CAST(DT_TRAMITACAO AS DATE), DEPARTAMENTO
ORDER BY CAST(DT_TRAMITACAO AS DATE), DEPARTAMENTO